name: unit tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.3.0

      - name: Install pnpm
        run: npm install -g pnpm@10

      - name: Install deps
        run: pnpm install

      - name: Run tests
        run: pnpm --filter ./apps/web test